name: form_steward_example
description: "A Flutter project demonstrating responsive multi-step forms using FormSteward. Includes custom stepper navigation, dynamic form loading from JSON, and layout adaptation for mobile, tablet, and desktop."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  form_steward:
    path: ../form_steward

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/form_config.json